### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:8765
Accept: application/json



### Identity Requests


GET /api/v1/identities
Host: localhost:8765
Accept: application/json
Authorization: Basic admin@gmail.com admin

###
GET /api/v1/identities/by-id?identityId=51d62f14-3b6a-42b7-b14c-e13462ed9181
Host: localhost:8765
Accept: application/json
Authorization: Basic admin@gmail.com admin

###
POST /api/v1/identities/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: NV0OG2Ta5SuiDzJIxLlaQFd3gtIZDaNrnST_dzyCn7H73CnmAD46LVHt0RqPbAZ8_ZRuczYVr-srP5BGrEDGEV61qYnN7hrQ

{
    "username": "director",
    "password": "director",
    "email": "director@gmail.com",
    "phone": "+7(888)-523-45-75"
}

###
PUT /api/v1/identities/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: CVSN10oGJmUietityGkspv0svHw-68t3xXdKgzEf69farvhaamy74CxkQFUPHuqdrkQYksUekUVc3_1a8RMp51Qm27O8mpxj

{
    "id": "fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b",
    "phone": "+7(666)-423-76-45"
}

###
DELETE /api/v1/identities/delete?identityId=fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b
Host: localhost:8765
Accept: text/plain
Authorization: Basic director@gmail.com director
X-Csrf-Token: maPT_H_H7Bsvls5qA2SYEseGj68y0nJYgvN7LdVd9WoIOJ9crMG1zRz32C0Co_ZcNkmsJaXgos4AsUB14cIZGuE5xV5pCvlu

###
PATCH /api/v1/identities/change-password?identityId=79c29119-72ae-46cf-86de-3e89531b3234
Host: localhost:8765
Content-Type: application/json
Authorization: Basic user@gmail.com user
X-Csrf-Token: 3XsEF3yjz9syb92vt6v4ngZL_8ylDMmxhz0pvKT2b5bGfxwF7Us1ck2T9r4fVridgYbM-mct0vTBaqqc4ghNi5zBXaTxGiVh

{
    "password": "user111"
}

###
PUT /api/v1/identities/make-director?identityId=fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: NV0OG2Ta5SuiDzJIxLlaQFd3gtIZDaNrnST_dzyCn7H73CnmAD46LVHt0RqPbAZ8_ZRuczYVr-srP5BGrEDGEV61qYnN7hrQ



### Corporation requests



### Sync
PUT /api/v1/corporations/add-director?
    corporationId=3eb603e8-8f74-43cb-ac8b-a4edd29f30cf&
    alreadyDirector=a0f65d48-15ae-4f3c-a0f7-7afd137e3c49&
    newDirector=bae9e303-8ff0-4bbe-ba0f-053ba344e9c8
Host: localhost:8765
Accept: text/plain
Authorization: Basic director@gmail.com director
X-Csrf-Token: jlIfkzFe0M8DTF52XzGQvqF-CQaGiqWT-M4auuyd9q-GWXNj72Qs8gE7sfgudDtAaxyk35hOJGe365S-wfh8jtX4lMuxYRBW

###
POST /api/v1/corporations/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: NV0OG2Ta5SuiDzJIxLlaQFd3gtIZDaNrnST_dzyCn7H73CnmAD46LVHt0RqPbAZ8_ZRuczYVr-srP5BGrEDGEV61qYnN7hrQ

{
    "name": "TeleSET Corp.",
    "description": "Описание корпорации TeleSET Corp.",
    "directorId": "fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b"
}

###
PUT /api/v1/corporations/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: dZNq1dOz9-tdC5LJVFST93mnNcYepVPWC4XzrszB8Jc3AvsPFPIPtLfWx4pwOab5YXmnkU_DGKculWr7MrbKyK35yKZWYcxr

{
    "id": "19897db2-00f9-4bfb-99a0-7497e17f336a",
    "name": "MediaSET Corp.",
    "description": "Описание корпорации MediaSET Corp.",
    "directorId": "fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b"
}

###
GET /api/v1/corporations
Host: localhost:8765
Accept: application/json

###
GET /api/v1/corporations/by-id?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json

###
DELETE /api/v1/corporations/delete?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: W64Fwaie-H2CwSm-xvHw2pCbi53bwH_S86hZBzB0MLvwpzWpbsxj8MuuzEuv9BGI89zE7fL9pvzpo03_kJk7MAQQAI-RlVOb



### Office Requests



###
GET /api/v1/offices/by-corporation?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json

###
GET /api/v1/offices/by-id
Host: localhost:8765
Accept: application/json
Content-Type: application/json

{
    "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
    "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
}

###
POST /api/v1/offices/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: fPtmbQB-6LevPEhHEgs6Y3hON1us0Rqs6mIpB2wV5d_JnBuvSZhSWzVJ3IaCX3xzKyYOUBksGmKe4ymB2wYQYQ4i0-f_riiZ

{
    "office": {
        "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a"
    },
    "newAddress": {
        "country": "Российская Федерация",
        "city": "Новосибирск",
        "street": "ул. Российская",
        "house": "15/1"
    }
}

###
PUT /api/v1/offices/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: W242V3qFWoeY2jTnIK9KH9f5V64hgRiuXAUVNj0fPVoFhxAIal4BZU-1aL617VWDGYJ-LuSdepcVsX6DOmciAg4sDjg04ylp

{
    "office": {
        "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
        "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
    },
    "newAddress": {
        "country": "Российская Федерация",
        "city": "Волгоград",
        "street": "ул. Митино",
        "house": "123"
    }
}

###
DELETE /api/v1/offices/delete
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: mCLl-6ILfVLTkSCtmzlAemLsV5opEGet0e_8t0b1eg9SaEA8rUCDysE7SWT-pBibrhR0TQCKevsbc1WAst6egHKRSjszWiYO

{
    "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
    "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
}



### Department Requests



###
GET /api/v1/departments/by-corporation?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/departments/by-id?departmentId=30a50aec-6820-4478-8e3f-046e8aaa2a22
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
POST /api/v1/departments/create
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director
Content-Type: application/json
X-Csrf-Token: bl3KR4a2hEUvs7jd_iqHYaf0Bgd72NaZJCNME673ooFJdhuqWz7-cbOBsHQC0IzpxwezUsaWKz5J6uW0FUd1dczAlLl_RCic

{
    "name": "Отдел Кадров",
    "description": "Описание отдела кадров",
    "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
    "officePKS": [
        {
            "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
            "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
        }
    ]
}

###
PUT /api/v1/departments/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
Content-Type: application/json
X-Csrf-Token: Jo6vAvVMA7nZURDEqteRGUTmF0hF0OtOAWuDYZnGToePW5xZR-_KY5EpM9j0YyT0n_qlf3KCOil14NJjOFi6B_j-drbuOKs9

{
    "id": "30a50aec-6820-4478-8e3f-046e8aaa2a22",
    "name": "Главный Отдел Кадров",
    "description": "Описание Главного Отдела Кадров"
}

###
DELETE /api/v1/departments/delete?departmentId=30a50aec-6820-4478-8e3f-046e8aaa2a22
Host: localhost:8765
Accept: text/plain
Authorization: Basic director@gmail.com director
X-Csrf-Token: -VW41Oh8Ycw6Sw_eGQ4rEcbQbS5ezz114pqIlZB_J_u1DycNzDfe5YtMVfoXfjfoLCMfJqS2QE9srA9YgavqoqQbF8_UPUE_



### Position Requests



###
GET /api/v1/positions/by-department?departmentId=30a50aec-6820-4478-8e3f-046e8aaa2a22
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/positions/by-corporation?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/positions/by-id?positionId=b67a56cc-dd23-40fc-9471-e8c6e531ead7
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
POST /api/v1/positions/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: bl3KR4a2hEUvs7jd_iqHYaf0Bgd72NaZJCNME673ooFJdhuqWz7-cbOBsHQC0IzpxwezUsaWKz5J6uW0FUd1dczAlLl_RCic

{
    "name": "Начальник Кадрового Отдела",
    "description": "Описание должности Начальника Кадрового Отдела",
    "departmentId": "30a50aec-6820-4478-8e3f-046e8aaa2a22"
}

###
PUT /api/v1/positions/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: 7UTT4pWRFcZJf4J2RAvpuBExvlre_aI3E9wa2QLtQlrp2g6-jCW2g_H0JadkTbZGcSbd3idVkzvuzZsaKu8jv2PVemuIuTna

{
    "id": "b67a56cc-dd23-40fc-9471-e8c6e531ead7",
    "name": "Начальник Главного Кадрового Отдела",
    "description": "Описание должности Начальника Главного Кадрового Отдела"
}

###
DELETE /api/v1/positions/delete?positionId=b67a56cc-dd23-40fc-9471-e8c6e531ead7
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: -ynNF5RX8YMPCoG-82mSJRAQNjLU-_FkUgTqq8y-Fea3v_gWzkurJvdnxbUiP7mIxkSmEnJ2G1PmmMNJMTWInPjaJdLWjZ4k



### Employee Requests



###
GET /api/v1/employees/by-corporation?corporationId=19897db2-00f9-4bfb-99a0-7497e17f336a
Host: localhost:8765
Accept: application/json
Authorization: Basic director@gmail.com director

###
GET /api/v1/employees/by-office
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director

{
    "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
    "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
}

###
POST /api/v1/employees/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: bl3KR4a2hEUvs7jd_iqHYaf0Bgd72NaZJCNME673ooFJdhuqWz7-cbOBsHQC0IzpxwezUsaWKz5J6uW0FUd1dczAlLl_RCic

{
    "identityId": "fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b",
    "positionId": "b67a56cc-dd23-40fc-9471-e8c6e531ead7",
    "firstName": "Палышев",
    "lastName": "Аркадий",
    "patronymic": "Викторович",
    "about": "Описание сотрудника и должность",
    "address": {
        "country": "Российская Федерация",
        "city": "Москва",
        "street": "ул. Мясницкая",
        "house": "125/4",
        "apartment": "54"
    },
    "office": {
        "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
        "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
    }
}

###
PUT /api/v1/employees/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: YHzR8JFzTI9Lwu1zHgylcsz9rdQd_nrbvcRKcjjLNi4MjIuiA0Tnx_cRKr9mpt9DeCGRRvTPgO1_ykz2iaApFl3yBkpquO-b

{
    "id": "1766dfce-0f45-4c94-88bf-758933e5e7b6",
    "identityId": "fc3e0ce7-f705-4e50-8e3f-1d956b6e9f5b",
    "firstName": "Рукольский",
    "lastName": "Руслан",
    "patronymic": "Владимирович",
    "office": {
        "corporationId": "19897db2-00f9-4bfb-99a0-7497e17f336a",
        "addressId": "79a9da7c-82cd-46db-94e2-d10a62dbeb4e"
    }
}

###
PATCH /api/v1/employees/office-transfer?employeeId=19d23b68-2c5f-4bbb-bf90-bfd15ea9871f
Host: localhost:8765
Accept: application/json
Content-Type: application/json
Authorization: Basic director@gmail.com director
X-Csrf-Token: eJ_ZxV-42kTGimOUFrr3Gk9Ypr7t_OyC-uAFsv_YgMTxV49wSa3s_GmI6HXrvAaiIJfDLi0-i4bfytyvzIY8gJq-sPDANu4U

{
    "corporationId": "dc088f82-db57-4bb1-9290-ea4ea4bedd90",
    "addressId": "acc8c398-483c-4977-877f-f0e5a086b2a4"
}

###
DELETE /api/v1/employees/delete?employeeId=1766dfce-0f45-4c94-88bf-758933e5e7b6
Host: localhost:8765
Accept: text/plain
Authorization: Basic director@gmail.com director
X-Csrf-Token: c60k-BnxDskEqx5gv-i6ryQGYr_GrjK6XsxcveyidnKT5f_9Rs9CyXrBOv8pniZWisWOmEZgT970zQCXPf0-itjGRkby15nP